services:
  - type: web
    name: privyloans
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && npm install && npm run build
    startCommand: gunicorn api:app
    healthCheckPath: /api/auth/me
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

